from __future__ import annotations

from typing import Any


METRIC_CATALOG: list[dict[str, Any]] = [
    {
        "id": "trajectory_frequency",
        "name": "Frequencia de trajetorias semelhantes",
        "formula": "contagem de instancias com origem, destino e distancia media entre formas dentro das tolerancias",
        "pdf_reference": "Produto 3, secoes 3.2 e 6; apoio visual a volume e utilizacao",
        "code_reference": "src/uam_dashboard/exports.py::tracks_geojson",
        "status": "implemented_configurable_clustering",
        "data_required": "simt, id, lat, lon, distflown",
    },
    {
        "id": "lowc_events",
        "name": "Loss of Well Clear",
        "formula": "Sh(t) < Smin_h and Sv(t) < Smin_v",
        "pdf_reference": "Produto 3, secao 4.2.1, Eq. 4.1",
        "code_reference": "src/uam_dashboard/metrics.py::detect_lowc_events",
        "status": "implemented",
        "data_required": "simt, id, lat, lon, alt",
    },
    {
        "id": "lowc_per_flight_hour",
        "name": "Taxa LoWC por hora de voo",
        "formula": "N_lowc / sum(H_f)",
        "pdf_reference": "Produto 3, secao 3.3, Eq. 3.2",
        "code_reference": "src/uam_dashboard/metrics.py::_safety_summary",
        "status": "implemented",
        "data_required": "duracao observada por aeronave",
    },
    {
        "id": "lowc_per_100_operations",
        "name": "Taxa LoWC por 100 operacoes",
        "formula": "N_lowc / N_voos * 100",
        "pdf_reference": "Produto 3, secao 3.3",
        "code_reference": "src/uam_dashboard/metrics.py::_safety_summary",
        "status": "implemented",
        "data_required": "id da aeronave",
    },
    {
        "id": "lowc_per_1000_km",
        "name": "Taxa LoWC por 1000 km",
        "formula": "N_lowc / km_voados * 1000",
        "pdf_reference": "Produto 3, secao 3.3",
        "code_reference": "src/uam_dashboard/metrics.py::_safety_summary",
        "status": "implemented",
        "data_required": "distflown",
    },
    {
        "id": "severity_ratio",
        "name": "Severidade de conflito",
        "formula": "sev_ij = min_t(Sh/Smin_h, Sv/Smin_v)",
        "pdf_reference": "Produto 3, secao 4.2.3, Eq. 4.5",
        "code_reference": "src/uam_dashboard/metrics.py::_summarize_lowc_event",
        "status": "implemented",
        "data_required": "simt, lat, lon, alt",
    },
    {
        "id": "time_below_threshold",
        "name": "Tempo abaixo do limiar",
        "formula": "amostras consecutivas em LoWC * passo de amostragem",
        "pdf_reference": "Produto 3, secao 4.2.3",
        "code_reference": "src/uam_dashboard/metrics.py::_summarize_lowc_event",
        "status": "implemented_as_sampled_estimate",
        "data_required": "simt regular ou amostragem configurada",
    },
    {
        "id": "nmac_events",
        "name": "Near Mid-Air Collision",
        "formula": "Sh(t) < S_NMAC_h and Sv(t) < S_NMAC_v",
        "pdf_reference": "Produto 3, secao 4.2.2",
        "code_reference": "src/uam_dashboard/metrics.py::_safety_summary",
        "status": "implemented_configurable_threshold",
        "data_required": "simt, lat, lon, alt",
    },
    {
        "id": "expected_mac",
        "name": "MAC esperado",
        "formula": "E[MAC] = N_NMAC * P(MAC|NMAC)",
        "pdf_reference": "Produto 3, secao 4.2.2, Eq. 4.2-4.4",
        "code_reference": "src/uam_dashboard/metrics.py::_safety_summary",
        "status": "implemented_as_sensitivity_band",
        "data_required": "NMAC e bandas configuradas",
    },
    {
        "id": "mean_flight_time_min",
        "name": "Tempo medio de voo",
        "formula": "mean(max(simt_f) - min(simt_f))",
        "pdf_reference": "Produto 3, secao 4.3.4",
        "code_reference": "src/uam_dashboard/metrics.py::efficiency_metrics",
        "status": "implemented_observed_proxy",
        "data_required": "simt, id",
    },
    {
        "id": "mean_distance_nm",
        "name": "Distancia media executada",
        "formula": "mean(max(distflown_f))",
        "pdf_reference": "Produto 3, secao 4.3.4",
        "code_reference": "src/uam_dashboard/metrics.py::efficiency_metrics",
        "status": "implemented",
        "data_required": "distflown, id",
    },
    {
        "id": "mean_route_efficiency_pct",
        "name": "Eficiencia horizontal",
        "formula": "d_gc / d_real * 100",
        "pdf_reference": "Produto 3, secoes 4.1 e 4.3.6",
        "code_reference": "src/uam_dashboard/metrics.py::efficiency_metrics",
        "status": "implemented_great_circle_proxy",
        "data_required": "lat/lon inicial e final, distflown",
    },
    {
        "id": "delay_metrics",
        "name": "Atrasos e pontualidade",
        "formula": "dependem de S_f, R_f, D_f, A_f e T_f",
        "pdf_reference": "Produto 3, secoes 4.3.1-4.3.3",
        "code_reference": "pendente de campos no log",
        "status": "unavailable_with_current_statelog",
        "data_required": "horarios planejados, autorizados e reais",
    },
    {
        "id": "trajectory_conformity",
        "name": "Conformidade de trajetoria",
        "formula": "comparacao entre rota planejada e trajetoria executada",
        "pdf_reference": "Produto 3, secao 4.3.5",
        "code_reference": "pendente de rota planejada",
        "status": "unavailable_with_current_statelog",
        "data_required": "geometria planejada ou dplan_f",
    },
]


def metric_catalog_payload() -> list[dict[str, Any]]:
    return METRIC_CATALOG
