from __future__ import annotations

from typing import Any


METRIC_CATALOG: list[dict[str, Any]] = [
    {
        "id": "trajectory_frequency",
        "name": "Frequencia de trajetorias semelhantes",
        "formula": "contagem de instancias com origem, destino e distancia media entre formas dentro das tolerancias",
        "pdf_reference": "Produto 3, secoes 3.2 e 6; apoio visual a volume e utilizacao",
        "code_reference": "src/uam_dashboard/exports.py::tracks_geojson",
        "status": "implemented_configurable_clustering",
        "data_required": "simt, id, lat, lon, distflown",
    },
    {
        "id": "lowc_events",
        "name": "Loss of Well Clear",
        "formula": "Sh(t) < Smin_h",
        "pdf_reference": "Produto 3 v1, criterio simplificado para separacao horizontal",
        "code_reference": "src/uam_dashboard/metrics.py::detect_lowc_events",
        "status": "implemented_horizontal_only",
        "data_required": "simt, id, lat, lon",
    },
    {
        "id": "lowc_per_flight_hour",
        "name": "Taxa LoWC por hora de voo",
        "formula": "N_lowc / sum(H_f)",
        "pdf_reference": "Produto 3, secao 3.3, Eq. 3.2",
        "code_reference": "src/uam_dashboard/metrics.py::_safety_summary",
        "status": "implemented",
        "data_required": "duracao observada por aeronave",
    },
    {
        "id": "lowc_per_100_operations",
        "name": "Taxa LoWC por 100 operacoes",
        "formula": "N_lowc / N_voos * 100",
        "pdf_reference": "Produto 3, secao 3.3",
        "code_reference": "src/uam_dashboard/metrics.py::_safety_summary",
        "status": "implemented",
        "data_required": "id da aeronave",
    },
    {
        "id": "lowc_per_1000_km",
        "name": "Taxa LoWC por 1000 km",
        "formula": "N_lowc / km_voados * 1000",
        "pdf_reference": "Produto 3, secao 3.3",
        "code_reference": "src/uam_dashboard/metrics.py::_safety_summary",
        "status": "implemented",
        "data_required": "distflown",
    },
    {
        "id": "severity_ratio",
        "name": "Severidade de conflito",
        "formula": "sev_ij = min_t(Sh/Smin_h)",
        "pdf_reference": "Produto 3 v1, severidade aplicada ao criterio horizontal simplificado",
        "code_reference": "src/uam_dashboard/metrics.py::_summarize_lowc_event",
        "status": "implemented_horizontal_only",
        "data_required": "simt, lat, lon",
    },
    {
        "id": "time_below_threshold",
        "name": "Tempo abaixo do limiar",
        "formula": "amostras consecutivas em LoWC * passo de amostragem",
        "pdf_reference": "Produto 3, secao 4.2.3",
        "code_reference": "src/uam_dashboard/metrics.py::_summarize_lowc_event",
        "status": "implemented_as_sampled_estimate",
        "data_required": "simt regular ou amostragem configurada",
    },
    {
        "id": "nmac_events",
        "name": "Near Mid-Air Collision",
        "formula": "Sh(t) < S_NMAC_h",
        "pdf_reference": "Produto 3 v1, criterio simplificado para separacao horizontal",
        "code_reference": "src/uam_dashboard/metrics.py::_safety_summary",
        "status": "implemented_configurable_horizontal_threshold",
        "data_required": "simt, lat, lon",
    },
    {
        "id": "expected_mac",
        "name": "MAC esperado",
        "formula": "MAC = 5.038e-3 * 0.005 * N_NMAC; MAC_100k = MAC / H_voo * 100000",
        "pdf_reference": "Produto 3 v1, seguranca; MAC estimado a partir de N_NMAC, beta e P(MAC|NMAC)",
        "code_reference": "src/uam_dashboard/metrics.py::_safety_summary",
        "status": "implemented_deterministic",
        "data_required": "NMAC horizontal e horas totais de voo",
    },
    {
        "id": "tls_margin",
        "name": "Margem em relacao ao TLS",
        "formula": "M_TLS = TLS / (lambda_MAC_obs + epsilon)",
        "pdf_reference": "Produto 3 v1, Eq. 4.12",
        "code_reference": "src/uam_dashboard/metrics.py::_safety_summary",
        "status": "implemented_configurable_tls",
        "data_required": "MAC estimado, horas totais de voo, TLS e epsilon",
    },
    {
        "id": "mean_flight_time_min",
        "name": "Tempo medio de voo",
        "formula": "mean(max(simt_f) - min(simt_f))",
        "pdf_reference": "Produto 3, secao 4.3.4",
        "code_reference": "src/uam_dashboard/metrics.py::efficiency_metrics",
        "status": "implemented_observed_proxy",
        "data_required": "simt, id",
    },
    {
        "id": "mean_distance_nm",
        "name": "Distancia media executada",
        "formula": "mean(max(distflown_f))",
        "pdf_reference": "Produto 3, secao 4.3.4",
        "code_reference": "src/uam_dashboard/metrics.py::efficiency_metrics",
        "status": "implemented",
        "data_required": "distflown, id",
    },
    {
        "id": "mean_route_efficiency_pct",
        "name": "Ineficiencia horizontal executada",
        "formula": "(d_real - d_gc) / d_gc * 100",
        "pdf_reference": "Produto 3, secao 4.3.6, Eq. 4.19",
        "code_reference": "src/uam_dashboard/metrics.py::efficiency_metrics",
        "status": "implemented",
        "data_required": "lat/lon inicial e final, distflown",
    },
    {
        "id": "delay_metrics",
        "name": "Atraso em solo",
        "formula": "GD_f = max(0, R_f - S_f)",
        "pdf_reference": "Produto 3, secao 4.3.1",
        "code_reference": "src/uam_dashboard/scenario_parser.py::ground_delay_metrics",
        "status": "implemented_by_paired_nominal_and_disturbed_scenarios",
        "data_required": "horarios de criacao nos SCNs nominal e perturbado",
    },
    {
        "id": "airborne_delay",
        "name": "Atraso no ar",
        "formula": "AD_f = max(0, (A_f - D_f) - T_f)",
        "pdf_reference": "Produto 3 v1, Eq. 4.14",
        "code_reference": "src/uam_dashboard/metrics.py::airborne_delay_metrics",
        "status": "implemented_by_paired_off_reference_log",
        "data_required": "tempos de primeira/ultima amostra do STATELOG avaliado e log OFF equivalente",
    },
    {
        "id": "total_delay",
        "name": "Atraso total",
        "formula": "TD_f = GD_f + AD_f",
        "pdf_reference": "Produto 3 v1, eficiencia; atraso total e pontualidade operacional",
        "code_reference": "src/uam_dashboard/metrics.py::total_delay_metrics",
        "status": "implemented_mean_ground_plus_airborne",
        "data_required": "atraso em solo e atraso no ar calculados",
    },
    {
        "id": "trajectory_conformity",
        "name": "Conformidade de trajetoria",
        "formula": "TC_f = (d_real - d_plan) / d_plan; ED_f = d_real - d_plan",
        "pdf_reference": "Produto 3, secao 4.3.5, Eq. 4.16-4.17",
        "code_reference": "src/uam_dashboard/metrics.py::trajectory_conformity",
        "status": "implemented",
        "data_required": "STATELOG executado e waypoints planejados do SCN",
    },
    {
        "id": "spatial_route_adherence",
        "name": "Aderencia espacial a REH",
        "formula": "amostras executadas com distancia a polilinha planejada <= tolerancia / amostras associadas * 100",
        "pdf_reference": "Diagnostico espacial complementar a secao 4.3.5",
        "code_reference": "src/uam_dashboard/metrics.py::trajectory_conformity",
        "status": "implemented_configurable_diagnostic",
        "data_required": "STATELOG executado e waypoints planejados do SCN",
    },
    {
        "id": "air_traffic_density",
        "name": "Densidade de trafego aereo",
        "formula": "ATD_dt = N_simultaneo_dt / A",
        "pdf_reference": "Produto 3 v1, Eq. 4.23",
        "code_reference": "src/uam_dashboard/capacity.py::capacity_metrics",
        "status": "implemented_reh_corridor_area",
        "data_required": "STATELOG, REH planejada e largura de corredor",
    },
    {
        "id": "complexity_components",
        "name": "Componentes de complexidade",
        "formula": "cruzamentos, waypoints, grupos recorrentes, LoWC e fluxos convergentes",
        "pdf_reference": "Produto 3 v1, secao 4.4.1",
        "code_reference": "src/uam_dashboard/capacity.py::_complexity_components",
        "status": "implemented_proxy_components",
        "data_required": "STATELOG, SCN, trajetorias agrupadas e LoWC",
    },
    {
        "id": "resource_throughput",
        "name": "Throughput por recurso",
        "formula": "THR_r,dt = N_r,dt / |dt|",
        "pdf_reference": "Produto 3 v1, Eq. 4.24",
        "code_reference": "src/uam_dashboard/capacity.py::_resource_throughput",
        "status": "implemented_one_hour_windows",
        "data_required": "instancias de voo, pares OD, grupos de trajetoria e REH planejada",
    },
    {
        "id": "resource_utilization",
        "name": "Utilizacao de recurso",
        "formula": "U_r,dt = N_r,dt / C_r,dt; C_r,dt = P95(THR_r,dt)",
        "pdf_reference": "Produto 3 v1, Eq. 4.25",
        "code_reference": "src/uam_dashboard/capacity.py::_resource_throughput",
        "status": "implemented_p95_nominal_capacity",
        "data_required": "throughput horario observado por tipo de recurso",
    },
    {
        "id": "risk_ratio",
        "name": "Razao de risco",
        "formula": "RR_s = MAC_100k_s / MAC_100k_ref",
        "pdf_reference": "Produto 3 v1, Eq. 4.10",
        "code_reference": "generate_dashboard.py::comparison_payload",
        "status": "implemented_reference_nominal_off",
        "data_required": "MAC_100k do cenario avaliado e do cenario sem intervencao/sem perturbacao",
    },
]


def metric_catalog_payload() -> list[dict[str, Any]]:
    return METRIC_CATALOG
