from __future__ import annotations

from typing import Any


METRIC_CATALOG: list[dict[str, Any]] = [
    {
        "id": "trajectory_frequency",
        "name": "Frequencia de trajetorias semelhantes",
        "formula": "contagem de instancias com origem, destino e distancia media entre formas dentro das tolerancias",
        "pdf_reference": "Produto 3, secoes 3.2 e 6; apoio visual a volume e utilizacao",
        "code_reference": "src/uam_dashboard/exports.py::tracks_geojson",
        "status": "implemented_configurable_clustering",
        "data_required": "simt, id, lat, lon, distflown",
    },
    {
        "id": "lowc_events",
        "name": "Loss of Well Clear",
        "formula": "Sh(t) < Smin_h and Sv(t) < Smin_v",
        "pdf_reference": "Produto 3, secao 4.2.1, Eq. 4.1",
        "code_reference": "src/uam_dashboard/metrics.py::detect_lowc_events",
        "status": "implemented",
        "data_required": "simt, id, lat, lon, alt",
    },
    {
        "id": "lowc_per_flight_hour",
        "name": "Taxa LoWC por hora de voo",
        "formula": "N_lowc / sum(H_f)",
        "pdf_reference": "Produto 3, secao 3.3, Eq. 3.2",
        "code_reference": "src/uam_dashboard/metrics.py::_safety_summary",
        "status": "implemented",
        "data_required": "duracao observada por aeronave",
    },
    {
        "id": "lowc_per_100_operations",
        "name": "Taxa LoWC por 100 operacoes",
        "formula": "N_lowc / N_voos * 100",
        "pdf_reference": "Produto 3, secao 3.3",
        "code_reference": "src/uam_dashboard/metrics.py::_safety_summary",
        "status": "implemented",
        "data_required": "id da aeronave",
    },
    {
        "id": "lowc_per_1000_km",
        "name": "Taxa LoWC por 1000 km",
        "formula": "N_lowc / km_voados * 1000",
        "pdf_reference": "Produto 3, secao 3.3",
        "code_reference": "src/uam_dashboard/metrics.py::_safety_summary",
        "status": "implemented",
        "data_required": "distflown",
    },
    {
        "id": "severity_ratio",
        "name": "Severidade de conflito",
        "formula": "sev_ij = min_t(Sh/Smin_h, Sv/Smin_v)",
        "pdf_reference": "Produto 3, secao 4.2.3, Eq. 4.5",
        "code_reference": "src/uam_dashboard/metrics.py::_summarize_lowc_event",
        "status": "implemented",
        "data_required": "simt, lat, lon, alt",
    },
    {
        "id": "severity_dimension",
        "name": "Dimensao dominante da severidade",
        "formula": "argmin(Sh/Smin_h, Sv/Smin_v)",
        "pdf_reference": "Derivada da severidade da Eq. 4.5 para diagnostico",
        "code_reference": "src/uam_dashboard/metrics.py::detect_lowc_events",
        "status": "implemented_diagnostic_classification",
        "data_required": "separacoes horizontal e vertical normalizadas",
    },
    {
        "id": "time_below_threshold",
        "name": "Tempo abaixo do limiar",
        "formula": "amostras consecutivas em LoWC * passo de amostragem",
        "pdf_reference": "Produto 3, secao 4.2.3",
        "code_reference": "src/uam_dashboard/metrics.py::_summarize_lowc_event",
        "status": "implemented_as_sampled_estimate",
        "data_required": "simt regular ou amostragem configurada",
    },
    {
        "id": "nmac_events",
        "name": "Near Mid-Air Collision",
        "formula": "Sh(t) < S_NMAC_h and Sv(t) < S_NMAC_v",
        "pdf_reference": "Produto 3, secao 4.2.2",
        "code_reference": "src/uam_dashboard/metrics.py::_safety_summary",
        "status": "implemented_configurable_threshold",
        "data_required": "simt, lat, lon, alt",
    },
    {
        "id": "expected_mac",
        "name": "MAC esperado",
        "formula": "E[MAC] = N_NMAC * P(MAC|NMAC)",
        "pdf_reference": "Produto 3, secao 4.2.2, Eq. 4.2-4.4",
        "code_reference": "src/uam_dashboard/metrics.py::_safety_summary",
        "status": "implemented_as_sensitivity_band",
        "data_required": "NMAC e bandas configuradas",
    },
    {
        "id": "mean_flight_time_min",
        "name": "Tempo medio de voo",
        "formula": "mean(max(simt_f) - min(simt_f))",
        "pdf_reference": "Produto 3, secao 4.3.4",
        "code_reference": "src/uam_dashboard/metrics.py::efficiency_metrics",
        "status": "implemented_observed_proxy",
        "data_required": "simt, id",
    },
    {
        "id": "mean_distance_nm",
        "name": "Distancia media executada",
        "formula": "mean(max(distflown_f))",
        "pdf_reference": "Produto 3, secao 4.3.4",
        "code_reference": "src/uam_dashboard/metrics.py::efficiency_metrics",
        "status": "implemented",
        "data_required": "distflown, id",
    },
    {
        "id": "mean_route_efficiency_pct",
        "name": "Ineficiencia horizontal executada",
        "formula": "(d_real - d_gc) / d_gc * 100",
        "pdf_reference": "Produto 3, secao 4.3.6, Eq. 4.19",
        "code_reference": "src/uam_dashboard/metrics.py::efficiency_metrics",
        "status": "implemented",
        "data_required": "lat/lon inicial e final, distflown",
    },
    {
        "id": "delay_metrics",
        "name": "Atraso em solo",
        "formula": "GD_f = max(0, R_f - S_f)",
        "pdf_reference": "Produto 3, secao 4.3.1, Eq. 4.10",
        "code_reference": "src/uam_dashboard/scenario_parser.py::ground_delay_metrics",
        "status": "implemented_by_paired_nominal_and_disturbed_scenarios",
        "data_required": "horarios de criacao nos SCNs nominal e perturbado",
    },
    {
        "id": "trajectory_conformity",
        "name": "Conformidade de trajetoria",
        "formula": "TC_f = (d_real - d_plan) / d_plan; ED_f = d_real - d_plan",
        "pdf_reference": "Produto 3, secao 4.3.5, Eq. 4.16-4.17",
        "code_reference": "src/uam_dashboard/metrics.py::trajectory_conformity",
        "status": "implemented",
        "data_required": "STATELOG executado e waypoints planejados do SCN",
    },
    {
        "id": "spatial_route_adherence",
        "name": "Aderencia espacial a REH",
        "formula": "amostras executadas com distancia a polilinha planejada <= tolerancia / amostras associadas * 100",
        "pdf_reference": "Diagnostico espacial complementar a secao 4.3.5",
        "code_reference": "src/uam_dashboard/metrics.py::trajectory_conformity",
        "status": "implemented_configurable_diagnostic",
        "data_required": "STATELOG executado e waypoints planejados do SCN",
    },
    {
        "id": "risk_ratio",
        "name": "Razao de risco",
        "formula": "RR = lambda_mitigado / lambda_referencia",
        "pdf_reference": "Produto 3, secao 4.2.5, Eq. 4.7",
        "code_reference": "generate_dashboard.py::comparison_payload",
        "status": "implemented_paired_mvp_vs_off",
        "data_required": "cenarios pareados com e sem MVP",
    },
]


def metric_catalog_payload() -> list[dict[str, Any]]:
    return METRIC_CATALOG
